#!/usr/bin/env python3

from __future__ import annotations

import pathlib
import unicodedata


ROOT = pathlib.Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "src" / "render" / "unicode-width.generated.ts"


def build_ranges(predicate):
    ranges = []
    start = None
    prev = None

    for codepoint in range(0x110000):
        if predicate(codepoint):
            if start is None:
                start = codepoint
                prev = codepoint
            elif codepoint == prev + 1:
                prev = codepoint
            else:
                ranges.append((start, prev))
                start = codepoint
                prev = codepoint
        elif start is not None:
            ranges.append((start, prev))
            start = None
            prev = None

    if start is not None:
        ranges.append((start, prev))

    return ranges


def format_ranges(name: str, ranges):
    lines = [f"export const {name}: ReadonlyArray<readonly [number, number]> = ["]
    for start, end in ranges:
        lines.append(f"  [0x{start:x}, 0x{end:x}],")
    lines.append("];")
    return "\n".join(lines)


def is_combining(codepoint: int) -> bool:
    category = unicodedata.category(chr(codepoint))
    return category in {"Mn", "Mc", "Me"}


def is_wide(codepoint: int) -> bool:
    category = unicodedata.category(chr(codepoint))
    if category == "Cn":
        return False
    return unicodedata.east_asian_width(chr(codepoint)) in {"W", "F"}


def main() -> None:
    combining = build_ranges(is_combining)
    wide = build_ranges(is_wide)

    contents = "\n".join([
        "// Generated by scripts/generate_unicode_width_table.py",
        f"// Unicode version: {unicodedata.unidata_version}",
        "// W/F ranges are derived from East_Asian_Width with unassigned code points excluded.",
        "",
        format_ranges("COMBINING_RANGES", combining),
        "",
        format_ranges("WIDE_RANGES", wide),
        "",
    ])

    OUTPUT.write_text(contents, encoding="utf-8")


if __name__ == "__main__":
    main()
